version: '3.1'

services:
  db:
    image: mysql:9.0
    restart: always
    environment:
      MYSQL_DATABASE: sample # 任意のデータベース
      MYSQL_ROOT_PASSWORD: example # 任意のパスワード
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./migration/my.conf:/etc/mysql/my.cnf
      - ./scripts/dummy_data:/dummy_data
volumes:
  db_data:
    driver: local